# Generated by Django 4.1.7 on 2023-03-12 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mailinglist_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="members",
            field=models.ManyToManyField(
                null=True, related_name="chats", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
