# Generated by Django 4.1.7 on 2023-03-12 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_chat_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="subscribers",
            field=models.ManyToManyField(
                null=True, related_name="subscriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
