# Generated by Django 4.1.7 on 2023-03-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_mailinglist_subscribers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("personal", "Personal"),
                            ("group", "Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_capacity", models.IntegerField(blank=True, default=1, null=True)),
                ("date_time", models.DateTimeField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.room",
                    ),
                ),
            ],
        ),
    ]
