# Generated by Django 4.1.7 on 2023-03-12 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="date_time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
