# Generated by Django 4.1.7 on 2023-03-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_date_time_lesson_start_time_lesson_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="instructor",
            new_name="trainer",
        ),
    ]
