# Generated by Django 4.1.7 on 2023-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_instructor_lesson_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
    ]
