# Generated by Django 4.1.7 on 2023-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client", "Client"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("trainer", "Trainer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
