# Generated by Django 4.1.7 on 2023-03-27 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
