# Generated by Django 4.1.7 on 2023-04-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_plantype_plan_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="plan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.plan"
            ),
        ),
    ]
