# Generated by Django 4.1.7 on 2023-04-10 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_financialrecord_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="mailing_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="api.mailinglist",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
