# Generated by Django 4.1.7 on 2023-04-11 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
