# Generated by Django 4.1.7 on 2023-04-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_mailinglist_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="subscriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
