# Generated by Django 4.1.7 on 2023-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_city_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="lat",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="city",
            name="long",
            field=models.FloatField(default=None),
        ),
    ]
